### ISSUE TITLE
Automatically create the chained certificate

### ISSUE THREAD

**Issue by ludovicc** [andreaswolf/ansible-role-letsencrypt#11]
For Nginx, concatenate the generated certificate with Letsencrypt intermediate cert.

**Comment by andreaswolf** [comment]
I would try solving this with an additional config parameter for the cert, or put the concatenated version into an additional file. What would you prefer?

**Comment by ludovicc** [comment]
An additional file is probably better, as it leaves the choice to the user after the generation of certificates. It's easier this way to switch from Apache to Nginx while keeping the same set of keys.
