### ISSUE TITLE
Minimum ansible version

### ISSUE THREAD

**Issue by skolsuper** [andreaswolf/ansible-role-letsencrypt#13]
Hi, firstly, thanks for making this.

The meta/main.yml describes the minimum ansible version as 1.2, but this fails on ansible 1 because of `checksum` in one task, which was an option added in v2 [docs](http://docs.ansible.com/ansible/get_url_module.html#options)

Its not a problem for me, but you might want to update your docs.

Thanks!

**Comment by andreaswolf** [comment]
Oh, you’re right. Initially, I used the Ansible 1.x-compatible checksum check, but that somehow got lost with a PR I guess. The "1.2" actually got inserted in the initial role, I did not really check it.

I’ll correct it ASAP, either by fixing the incompatibility or by raising the version number. Thanks for the hint!

**Comment by andreaswolf** [comment]
Fixed by using sha256 instead of checksum.
