### ISSUE TITLE
Incomplete Renew Certs Cron Job

### ISSUE THREAD

**Issue by smuriu** [andreaswolf/ansible-role-letsencrypt#29]
Current cron template `renew-certs.py` skips two major steps:
- Does not regenerate the chained or full chained cert necessary for some web servers
- Does not restart the web server after renewing the certificates

**Comment by smuriu** [comment]
Just noticed pull request #28 seems to address the first issue

**Comment by andreaswolf** [comment]
Correct. I’d like to close this one therefore :)
