### ISSUE TITLE
Running role more than once errors

### ISSUE THREAD

**Issue by SuperQ** [andreaswolf/ansible-role-letsencrypt#6]
If you try and re-play the role, it fails. :-(

```
TASK [andreaswolf.letsencrypt : generate the initial certificate] **************
fatal: [XXXX]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check ''error' in generate_initial_cert.stdout or 'Error' in generate_initial_cert.stdout or 'Error' in generate_initial_cert.stderr' failed. The error was: ERROR! an unexpected type error occurred. Error was argument of type 'bool' is not iterable"}
```

**Comment by andreaswolf** [comment]
Weird. Could you paste the contents of /var/lib/letsencrypt/renew-certs.py? You can of course anonymize it if necessary…

**Comment by andreaswolf** [comment]
I just realized that I had some unpushed commits lurking on my harddisk. If you check again with current master, it might work already…

**Comment by ludovicc** [comment]
I do not see this problem any more.

**Comment by andreaswolf** [comment]
Me neither, so I’m closing this for now. @SuperQ and others: feel free to reopen it in case the error occurs again!
